### ISSUE TITLE
Automatic npm releases via Travis CI

### ISSUE THREAD

**Issue by bennyn** [HyperCubeProject/binance-api-node#92]
To speed up development it would be nice if this project here automatically creates versions on npm when a PR is merged to master. 😃 

This behaviour is supported by Travis CI: 
- https://docs.travis-ci.com/user/deployment/npm/

Here is a sample config:

**.travis.yml**

```yml
# https://docs.travis-ci.com/user/deployment/npm/
deploy:
  api_key:
    secure: ...
  email:
    secure: ...
  provider: npm
  skip_cleanup: true
  on:
    tags: true
```

**package.json**

```json
"scripts": {
    "postversion": "git push && git push --tags",
    "preversion": "yarn && yarn dist && yarn test",
    "version": "yarn dist"
}
```
